name: Deploy Test Lambda For Extractors

on:
  pull_request:
    branches:
      - dev

jobs:
  dispatch-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Extractor Tests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflows = {
              "extract/clien": "clien-extract-test.yml",
              "extract/dcinside": "dcinside-extract-test.yml",
              "extract/bobaedream": "bobaedream-extract-test.yml"
            };

            const sourceBranch = "${{ github.event.pull_request.head.ref }}";  // ✅ PR 출발 브랜치 확인
            console.log("PR is coming from:", sourceBranch);

            if (workflows[sourceBranch]) {
              console.log(`Triggering workflow: ${workflows[sourceBranch]}`);
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflows[sourceBranch],
                ref: "dev"
              });
            } else {
              console.log("No matching workflow found for this branch.");
            }